---
fcoin:
  endpoints:
    public:
      PublicServerTime: "public/server-time"
      PublicCurrencies: "public/currencies"
      PublicSymbols: "public/symbols"
    market:
      MarketTicker: "market/ticker"
      MarketDepth: "market/depth"
      MarketTrades: "market/trades"
      MarketCandles: "market/candles"
    orders:
      CreateOrderLimit: "orders"
      OrderList: "orders"
      ReferenceOrder: "orders"
      CancelOrder: "orders"
      OrderMatchResults: "orders"
